// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7hUD8rK67K1zMqFa6qTzH-W894iaSGdg',
    appId: '1:963529889996:web:e285b7c070e2aa6b82ca69',
    messagingSenderId: '963529889996',
    projectId: 'autenticacion-49b79',
    authDomain: 'autenticacion-49b79.firebaseapp.com',
    storageBucket: 'autenticacion-49b79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFbK066tV98Hq57ZYIuoX6H1mOSb0XExg',
    appId: '1:963529889996:android:03b4de1860d6619682ca69',
    messagingSenderId: '963529889996',
    projectId: 'autenticacion-49b79',
    storageBucket: 'autenticacion-49b79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjf81oKuxN_mF-kaCVUp5Nw342F4ijo8U',
    appId: '1:963529889996:ios:8e9f3c50b780d73d82ca69',
    messagingSenderId: '963529889996',
    projectId: 'autenticacion-49b79',
    storageBucket: 'autenticacion-49b79.appspot.com',
    iosBundleId: 'com.example.countertes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjf81oKuxN_mF-kaCVUp5Nw342F4ijo8U',
    appId: '1:963529889996:ios:c0b6de24564f8d6082ca69',
    messagingSenderId: '963529889996',
    projectId: 'autenticacion-49b79',
    storageBucket: 'autenticacion-49b79.appspot.com',
    iosBundleId: 'com.example.countertes.RunnerTests',
  );
}
